# Generated by Django 5.2.5 on 2025-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=7)),
                ('check_id', models.CharField(max_length=7)),
                ('check_item', models.CharField(max_length=30)),
                ('done', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Check list',
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=7)),
                ('custommer', models.CharField(max_length=30)),
                ('car', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('calculated_hours', models.TextField()),
                ('completed', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Job card',
            },
        ),
        migrations.CreateModel(
            name='PartsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=7)),
                ('part_id', models.CharField(max_length=7)),
                ('part_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Parts list',
            },
        ),
    ]
