# Generated by Django 5.2.5 on 2025-09-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='worked_hours',
            field=models.CharField(default='hi', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='calculated_hours',
            field=models.CharField(max_length=5),
        ),
    ]
