# Generated by Django 5.2.5 on 2025-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_jobcard_worked_hours_alter_jobcard_calculated_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_price', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
