# Generated by Django 5.2.5 on 2025-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=7)),
                ('calculated_bool', models.CharField(max_length=2)),
                ('time_registry', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Check list',
            },
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='calculated_hours',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='worked_hours',
        ),
    ]
