# Generated by Django 5.2.5 on 2025-09-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_timetable_remove_jobcard_calculated_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name_plural': 'Time table'},
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_id',
            field=models.CharField(default='hi', max_length=5),
            preserve_default=False,
        ),
    ]
