# Generated by Django 5.2.5 on 2025-09-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_timetable_options_timetable_time_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=30)),
                ('car', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Customer table',
            },
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='car',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='custommer',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_id',
            field=models.CharField(default='hi', max_length=7),
            preserve_default=False,
        ),
    ]
