# Generated by Django 5.2.5 on 2025-09-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_customertable_remove_jobcard_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='car',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='license_plate',
            field=models.CharField(default='hi', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='name',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
    ]
