# Generated by Django 5.2.5 on 2025-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_jobcard_car_jobcard_license_plate_jobcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='hour_price',
            field=models.CharField(default='hi', max_length=7),
            preserve_default=False,
        ),
    ]
