# Generated by Django 5.2.5 on 2025-09-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_jobcard_hour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
