# Generated by Django 5.2.5 on 2025-09-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_customertable_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='car',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='name',
        ),
    ]
